edition = "2023";

package keeper.v1;

option go_package = "github.com/ArtShib/gophkeeper/gen/go/keeper/v1;keeperv1";

import "keeper/v1/common.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service SecretService {
  rpc CreateSecret(CreateSecretRequest) returns (CreateSecretResponse);
  rpc ListSecrets(ListSecretsRequest) returns (ListSecretsResponse);
  rpc UpdateSecret(UpdateSecretRequest) returns (google.protobuf.Empty);
  rpc DeleteSecret(DeleteSecretRequest) returns (google.protobuf.Empty);
}

message Secret {
  string id = 1;
  SecretMetadata meta = 2;
  bytes encrypted_data = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  bool is_deleted = 6;
}

message CreateSecretRequest {
  SecretMetadata meta = 1;
  bytes encrypted_data = 2;
}

message CreateSecretResponse {
  string id = 1;
}

message ListSecretsRequest {}

message ListSecretsResponse {
  repeated Secret secrets = 1;
}

message UpdateSecretRequest {
  string id = 1;
  SecretMetadata meta = 2;
  bytes encrypted_data = 3;
}

message DeleteSecretRequest {
  string id = 1;
}
